version: "3"
services:
  go:
    container_name: go.local
    image: golang:1.21-bookworm
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
  mysql:
    container_name: go.mysql.local
    image: mysql:8.0
    # for m1 mac
    platform: linux/x86_64
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql:delegated
      - ./docker/mysql/conf/my80.cnf:/etc/mysql/my.cnf:cached
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:cached
volumes:
  db-data:
    driver: local
